### ISSUE TITLE
Use ©, instead of @ for copyright text.

### ISSUE THREAD

**Issue by stevestock** [saschpe/android-versioninfo#2]
I think it is more correct to use ©, instead of @ as a copyright symbol.

The fix is simple, and involves changing `\@` to `\u00A9` in @string/copyright_template

I submitted pull request #1 

For anyone else experiencing this issue, you can manually overwrite the string in your `res/values/strings.xml`:

```
...
<string name="copyright_template">\u00A9<xliff:g id="copyright-year" example="2015">%1$tY</xliff:g> <xliff:g id="copyright-owner" example="Sascha Peilicke">%2$s</xliff:g></string>
...
```

**Comment by saschpe** [comment]
Fixed

**Comment by stevestock** [comment]
Thanks @saschpe !
